name: dcss
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - leidenalg
  - seaborn
  - matplotlib
  - scikit-learn
  - spacy
  - pymc3
  - pip
  - numpy
  - beautifulsoup4
  - networkx
  - python-louvain
  - pyyaml
  - graphviz
  - pip:
    - dcss
    - lxml
